### ISSUE TITLE
"ReferenceError: Can't find variable: Proxy"

### ISSUE THREAD

**Issue by lewisainslie** [sigtm/Framer-Adapt#4]
Experiencing the error "ReferenceError: Can't find variable: Proxy" when I view a prototype on a smaller device (iPhone 5S) in this case. But it works perfectly fine on a iPhone 6S Plus. 

Works fine in both of the View's on the Macbook that is.

```javascript
{Adapt} = require 'Adapt'

Adapt.text =
	xsmall: "iPhone5"
	small: "iPhone7"
	medium: "iPad"

Adapt.setBreakpoints
	xsmall: 320
	small: 414
	medium: 768

if Adapt.text == "iPhone5"
	print "iphone5"
if Adapt.text == "iPhone7"
	print "iphone7"	

```

**Comment by sigtm** [comment]
Ah, thanks for the heads up, I will look into it. Which iOS version is the 5s running on?

The JavaScript Proxy object is a relatively recent thing, so it may not be supported on all versions of iOS I suppose.

**Comment by lewisainslie** [comment]
The device is currently sitting on 9.2.1. May try update it and see if that resolves the issue. Will check back. Thanks! 

Edit: That was the case, tried it on a 5S with a new version of iOS and the issue is gone. Any idea on how to resolve it for older versions of iOS?

**Comment by sigtm** [comment]
Thanks, that would be really helpful. Judging by the table at the bottom of the MDN reference page it's at least only officially supported since iOS 10:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Hadn't checked that before – I don't know of any workarounds that would allow the same syntax without using a proxy object, but I should at least make a note of it in the readme.

**Comment by lewisainslie** [comment]
That was the case. The older version of iOS the error was displayed but the latest fixed it.

**Comment by sigtm** [comment]
Cool, nice catch :) Added a link to a compatibility table to the readme in case anyone else anyone else has the same problem.
